name: ComplexRedstone
main: com.namarius.complexredstone.ComplexRedstone
version: 0.0.0.0
author: Namarius
database: false
commands:
  crmore:
    description: Allows section based output over the last ComplexRedstone command.
    usage: /<command> [] number of lines,[x] output x till max x+20,[x,y] output x till max x+y
  crcom:
    description: Saving a command that is longer than possible and sending it out if // is found
    usage: /<command> [command, //(Send Command), param] ...
  crstart:
    description: textextext
    usage: /<command> textextext
  crend:
    description: textextext
    usage: /<command> textextext
  crstep:
    description: textextext
    usage: /<command> textextext
  crarm:
    description: textextext
    usage: /<command> textextext
  crfuse:
    description: textextext
    usage: /<command> textextext
  crlist:
    description: textextext
    usage: /<command> textextext
  cradd:
    description: textextext
    usage: /<command> textextext
  crdelete:
    description: textextext
    usage: /<command> textextext
  craddset:
    description: textextext
    usage: /<command> textextext
  crdeleteset:
    description: textextext
    usage: /<command> textextext
  crswitchset:
    description: textextext
    usage: /<command> textextext
  crenable:
    description: textextext
    usage: /<command> textextext
  crdisable:
    description: textextext
    usage: /<command> textextext
  crforcedisable:
    description: textextext
    usage: /<command> textextext
  
  