name: Backforge
main: com.namarius.complexredstone.ComplexRedstone
version: 0.0.0
author: Namarius
database: false
commands:
  crcom:
    description: textextext
    usage: /<command> textextext
  crstart:
    description: textextext
    usage: /<command> textextext
  crend:
    description: textextext
    usage: /<command> textextext
  crstep:
    description: textextext
    usage: /<command> textextext
  crarm:
    description: textextext
    usage: /<command> textextext
  crfuse:
    description: textextext
    usage: /<command> textextext
  crlist:
    description: textextext
    usage: /<command> textextext
  cradd:
    description: textextext
    usage: /<command> textextext
  crdelete:
    description: textextext
    usage: /<command> textextext
  craddset:
    description: textextext
    usage: /<command> textextext
  crdeleteset:
    description: textextext
    usage: /<command> textextext
  crswitchset:
    description: textextext
    usage: /<command> textextext
  crenable:
    description: textextext
    usage: /<command> textextext
  crdisable:
    description: textextext
    usage: /<command> textextext
  crforcedisable:
    description: textextext
    usage: /<command> textextext
  
  